### PR TITLE
Add database schema

### PR DESCRIPTION
**Pull request by mfcrocker**
Creates and automigrates to the database schema specified in the ERD

**How to test**
Deploy to your sandbox, check the logs to ensure there aren't any errors, then port forward to your DB and check you have the surveyv2 schema

image

### CODE REVIEW

**Comment by ghost** [comment]
@mfcrocker, Spinnaker is deploying the PR to your environment

**Comment by ghost** [comment]
@mfcrocker, Spinnaker is deploying the PR to your environment

**Comment by ghost** [comment]
@mfcrocker, Spinnaker is deploying the PR to your environment

**Comment by ghost** [comment]
@mfcrocker, Spinnaker is deploying the PR to your environment

**Comment by ghost** [comment]
@mfcrocker, Spinnaker is deploying the PR to your environment

**Comment by ghost** [comment]
@mfcrocker, Spinnaker is deploying the PR to your environment

**Comment by ghost** [comment]
@mfcrocker, Spinnaker is deploying the PR to your environment

**Comment by ghost** [comment]
@mfcrocker, Spinnaker is deploying the PR to your environment

**Comment by ghost** [comment]
@mfcrocker, Spinnaker is deploying the PR to your environment

**Comment by ghost** [comment]
@mfcrocker, Spinnaker is deploying the PR to your environment

**Comment by ghost** [comment]
@mfcrocker, Spinnaker is deploying the PR to your environment

**Comment by ghost** [comment]
@mfcrocker, Spinnaker is deploying the PR to your environment

**Comment by ghost** [comment]
@mfcrocker, Spinnaker is deploying the PR to your environment

**Comment by ghost** [comment]
@mfcrocker, Spinnaker is deploying the PR to your environment

**Comment by ghost** [comment]
@mfcrocker, Spinnaker is deploying the PR to your environment

**Comment by ghost** [comment]
@mfcrocker, Spinnaker is deploying the PR to your environment

**Comment by ghost** [comment]
@mfcrocker, Spinnaker is deploying the PR to your environment

**Comment by ghost** [comment]
@mfcrocker, Spinnaker is deploying the PR to your environment

**Comment by ghost** [comment]
@mfcrocker, Spinnaker is deploying the PR to your environment

**Comment by ghost** [comment]
@mfcrocker, Spinnaker is deploying the PR to your environment

**Comment by ghost** [comment]
@mfcrocker, Spinnaker is deploying the PR to your environment

**Comment by ghost** [comment]
@mfcrocker, Spinnaker is deploying the PR to your environment

**Comment by ghost** [comment]
@mfcrocker, Spinnaker is deploying the PR to your environment

**Comment by ghost** [comment]
@mfcrocker, Spinnaker is deploying the PR to your environment

**Comment by ghost** [comment]
@mfcrocker, Spinnaker is deploying the PR to your environment

**Comment by ghost** [comment]
@mfcrocker, Spinnaker is deploying the PR to your environment

**Comment by ghost** [comment]
@mfcrocker, Spinnaker is deploying the PR to your environment

**Review by anwilkie — APPROVED** [review]

**Pull request merged**
